ln:
	ln -f ../../../snippets/js/jquery.min.js
	ln -f ../../../snippets/js/bootstrap.min.js
	ln -f ../../../snippets/js/dygraph-combined.js
	ln -f ../../../snippets/js/ace.js
	ln -f ../../../snippets/js/util.js
	ln -f ../../../snippets/js/draw.js
	ln -f ../../../snippets/js/mouse3d.js
	ln -f ../../../snippets/vct/js/vct.js
	ln -f ../../../snippets/vct/js/mat.js
	ln -f ../../../snippets/md/js/mdutil.js
	ln -f ../../../snippets/lj/js/ljeos.js
	ln -f ../../../snippets/wl/js/wl.js
